const IMAGE_MAX_BYTES = 50 * 1024 * 1024;
const IMAGE_SNIFF_BYTES = 4096;
const SNIFF_CONCURRENCY = 8;
const LOCAL_PERSIST_CONCURRENCY = 4;
const NETWORK_CHUNK_FILES = 25;
const SCRAPE_IMPORT_URLS_CHUNK = 200;
const NETWORK_UPLOAD_CONCURRENCY = 4;
export {
  IMAGE_MAX_BYTES,
  IMAGE_SNIFF_BYTES,
  LOCAL_PERSIST_CONCURRENCY,
  NETWORK_CHUNK_FILES,
  NETWORK_UPLOAD_CONCURRENCY,
  SCRAPE_IMPORT_URLS_CHUNK,
  SNIFF_CONCURRENCY
};
